version: '3.5'

services:
  localstack:
    container_name: lanchonete_localstack
    image: localstack/localstack
    ports:
     - "4566:4566"            # LocalStack Gateway
     - "4510-4559:4510-4559"  # external services port range
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      AWS_REGION: us-east-1