version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - pagamentos_network
    expose:
      - 5432
  mock:
    build:
      context: wiremock
    image: wiremock/wiremock
    ports:
      - "8081:8080"
    networks:
      - pagamentos_network
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/logs:/home/wiremock/logs

  localstack:
    container_name: pagamentos_localstack
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"
    networks:
      - pagamentos_network  # external services port range
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
      AWS_REGION: us-east-1

networks:
  pagamentos_network:
    name: "pagamentos_network"
    driver: bridge