server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432/postgres}?stringtype=unspecified
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  sql:
    init:
      mode: always
logging:
  level:
    org:
      springframework:
        web: debug
      hibernate: error

springdoc:
  swagger-ui:
    operations-sorter: method

pagamentos:
  openapi:
    dev-url: http://localhost:8084
  queue: sqsPagamentos

mercadopago:
  api:
    url: ${MERCADOPAGO_URL_PAGAMENTOS:https://api.mercadopago.com/merchant_orders/}
    token: ${AUTHORIZATION_TOKEN_MERCADOPAGO:TEST-1391732842356404-082915-54d1af5cde66c321c38bddda2f7da865-92326974}

