apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  labels:
    app: pagamentos
spec:
  template:
    metadata:
      name: pagamentos
      labels:
        app: pagamentos
    spec:
      serviceAccountName: pagamentos-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: pagamentos-secrets
        - name: pagamentos-volume
          hostPath:
            path: /home/pagamentos-volume
            type: DirectoryOrCreate
      containers:
        - name: auth
          image: vwnunes/tech-challenge-61-pagamentos:latest
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pagamentos-secrets-aws
                  key: postgresHost
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pagamentos-secrets-aws
                  key: postgresUser
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pagamentos-secrets-aws
                  key: postgresPassword
          volumeMounts:
            - name: pagamentos-volume
              mountPath: /mnt/pagamentos-volume
            - name: secrets-store-inline
              mountPath: "/mnt/pagamentos-secrets"
              readOnly: true
  replicas: 2
  selector:
    matchLabels:
      app: pagamentos