apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pagamentos-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/tech-challenge-pagamentos/dev/DB_HOST"
        objectType: "ssmparameter"
        objectAlias: postgresHost
      - objectName: "/tech-challenge-pagamentos/dev/DB_USERNAME"
        objectType: "ssmparameter"
        objectAlias: postgresUser
      - objectName: "/tech-challenge-pagamentos/dev/DB_PASSWORD"
        objectType: "ssmparameter"
        objectAlias: postgresPassword
  secretObjects:
    - secretName: pagamentos-secrets-aws
      type: Opaque
      data:
        - objectName: postgresHost
          key: postgresHost
        - objectName: postgresUser
          key: postgresUser
        - objectName: postgresPassword
          key: postgresPassword